/home/luc/hgwork/lino/docs/admin/index.rst:24: WARNING: toctree contains reference to nonexisting document u'admin/ :maxdepth: 2'
/home/luc/hgwork/lino/docs/api/lino.modlib.cal.workflows.rst:21: WARNING: autodoc: failed to import module u'lino.modlib.cal.workflows.feedback'; the following exception was raised:
Traceback (most recent call last):
  File "/home/luc/pythonenvs/py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/luc/hgwork/lino/lino/modlib/cal/workflows/feedback.py", line 62, in <module>
    add('30', _("Rejected"),'rejected')
  File "/home/luc/hgwork/lino/lino/core/choicelists.py", line 403, in add_item
    return cls.add_item_instance(cls.item_class(value,text,name,*args,**kw))
  File "/home/luc/hgwork/lino/lino/core/choicelists.py", line 410, in add_item_instance
    raise Exception("Duplicate value %r in %s." % (i.value,cls))
Exception: Duplicate value u'30' in cal.GuestStates.
/home/luc/hgwork/lino/docs/todo.rst:1010: WARNING: Enumerated list ends without a blank line; unexpected unindent.
/home/luc/hgwork/lino/docs/blog/2013/0821/bug.rst:: WARNING: document isn't included in any toctree
/home/luc/hgwork/lino/lino/site.py:docstring of lino.site.Site.webdav_url:7: WARNING: term not in glossary: runserver
/home/luc/hgwork/lino/docs/changes.rst:76: WARNING: undefined label: welfare.debts.printliabilitiesbybudget (if the link has no caption the label must precede a section header)
/home/luc/hgwork/lino/docs/releases/index.rst:1: WARNING: unknown document: 1.6.11
